# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171121_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('nome', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('carga_horaria', models.SmallIntegerField()),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('conteudo', models.TextField()),
                ('bibliografia_complementar', models.TextField()),
                ('bibliografia_basica', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
    ]
