# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disciplina_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('ano', models.ForeignKey(db_column='ano', on_delete=django.db.models.deletion.CASCADE, related_name='ano_grade', to='core.GradeCurricular')),
                ('curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.CASCADE, to='core.GradeCurricular')),
                ('semestre', models.ForeignKey(db_column='semestre', on_delete=django.db.models.deletion.CASCADE, related_name='semestre_grade', to='core.GradeCurricular')),
            ],
        ),
    ]
