# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professor_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecurricular',
            name='curso',
            field=models.ForeignKey(db_column='curso', on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='curso',
            field=models.ForeignKey(db_column='curso', on_delete=django.db.models.deletion.CASCADE, to='core.GradeCurricular'),
        ),
    ]
